### ISSUE TITLE
Windows Memory Leak

### ISSUE THREAD

**Issue by lithiumfrost** [iffy/nim-keyring#16]
Microsoft's documentation (assuming I am reading correctly) says that Credfree needs to be called on the returned PCREDENTIALW object. I think the current code is holding the returned buffer indefinitely.

https://learn.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credfree

**Comment by iffy** [comment]
Thanks for the PR that fixed this in the latest version!
