### ISSUE TITLE
Any user process on MacOS has access to the secrets in keyring

### ISSUE THREAD

**Issue by markspanbroek** [iffy/nim-keyring#5]
Thanks for creating this library. I think I may have found a security issue.

On MacOS the `security` command line tool is invoked to add a generic password to the MacOS keychain. This results in a password entry in keychain where the access control is such that the `security` command line tool can always access the password (see attached screenshot). This means that any user process can simply invoke the `security` tool to retrieve a password that is saved using nim-keyring.

<img width="646" alt="Screenshot 2020-04-01 at 13 48 14" src="https://user-images.githubusercontent.com/1766771/78134310-37132b00-7420-11ea-91ff-2e8fe09d0be9.png">

Possible mitiigations:
- Supply the `-T ""` option when adding a password to the keychain (see `security add-generic-password --help`).
- Use the [Keychain API](https://developer.apple.com/documentation/security/keychain_services/keychain_items/adding_a_password_to_the_keychain) instead of the `security` command line tool.

**Comment by iffy** [comment]
Thank you for reporting this!  I'd rather use the Keychain API but haven't done the work yet. I'll look into both your proposed solutions (unless someone beats me to it with a PR)

**Comment by iffy** [comment]
It looks like using `-T` with any value won't work (I tried both `""` and `getAppFilename()`) because retrieving the password always happens with `security` and if a user chooses to Always Allow access it ends up in the insecure state you've described.  I'll have to use the Keychain API to fix this properly.

**Comment by iffy** [comment]
I think this is fixed -- are you able to verify with the newest version (v0.2.0)?

**Comment by markspanbroek** [comment]
Thanks for the fix! I now see that my own process is given access to the password, as expected.
I do run into an issue with retrieving the password, probably related to #7.

**Comment by iffy** [comment]
@markspanbroek Okay, how does v0.2.1 do?

Thanks again for the tip on CFData -- I would have spent a long time barking up the wrong tree.

**Comment by markspanbroek** [comment]
Glad I could help. v0.2.1 works like a charm! Thanks for fixing it.
