### ISSUE TITLE
segv with getPassword

### ISSUE THREAD

**Issue by iffy** [iffy/nim-keyring#7]
```
/Users/matt/m/nim-keyring/src/keyring/macos.nim(70) getPassword
/Users/matt/m/nim-keyring/src/keyring/macos_keyringapi.nim(109) $
/Users/matt/m/nim-keyring/src/keyring/macos_keyringapi.nim(106) getCFData
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by markspanbroek** [comment]
I notice slightly different behavior when I invoke getPassword: the process is hanging indefinitely.

**Comment by iffy** [comment]
@markspanbroek What macOS version and what Nim version?  I'm on macOS 10.14.6 with Nim 1.0.6

**Comment by markspanbroek** [comment]
I'm on MacOS 10.15.4 and tried with both Nim 1.0.6 and 1.2.0.

I've done some digging, and I think I've narrowed down the problem a bit. When I modify the test for the CFData roundtrip to use a string that's five times as long as the "hello world!" string, then I see the segv in the tests. There seems to be something weird going on with the CFDataGetBytes call, and the CFRange that is used there.

**Comment by iffy** [comment]
Thanks for finding the problem in CFData roundtrip.

If fixing the CFData bug is too tricky, I might explore using this instead: https://developer.apple.com/documentation/security/1398366-seckeychainaddgenericpassword?language=objc It's what python-keyring uses and it seems much simpler.
